### ISSUE TITLE
Rename `path` to `merkle_path` in cw-context for verify (non)membership

### ISSUE THREAD

**Issue by srdtrk** [cosmos/ibc-rs#1291]
## Feature Summary

Recently, ibc-go broke contract API [here](https://github.com/cosmos/ibc-go/pull/6924/files#diff-bd0618ba11fca65b87c57f68bf9cbba25ee07b82cc8bb56579744709a2e27d11L78). This means that `path` field of MsgVerify(Non)Membership should be renamed to `merkle_path`.

This api breaking change in ibc-go was made because the path field was changed from `[]string` to `[][]byte`. However, without the api breaking change, the json serialization of `[][]byte` is the same as `[]string` where the string is `base64` instead of utf-8. This would be an issue because an older wasm contract might treat base64 as utf-8 and prove non-membership when it shouldn't.

## Proposal

I can open a PR renaming the field

**Comment by Farhad-Shabani** [comment]
Thank you, @srdtrk. Feel free to go ahead with the PR.

**Comment by Farhad-Shabani** [comment]
Just to confirm @srdtrk ,the current raw [`Verify(non)MembershipMsgRaw`](https://github.com/cosmos/ibc-rs/blob/94f19e6685b2c6be0cd3f5d92c7bc89fa83803f2/ibc-clients/cw-context/src/types/msgs.rs#L122-L130), which brings in messages from the VM, uses the [MerklePath](https://github.com/cosmos/ibc-rs/blob/94f19e6685b2c6be0cd3f5d92c7bc89fa83803f2/ibc-clients/cw-context/src/types/msgs.rs#L125). However, the domain [`Verify(non)MembershipMsg`](https://github.com/cosmos/ibc-rs/blob/94f19e6685b2c6be0cd3f5d92c7bc89fa83803f2/ibc-clients/cw-context/src/types/msgs.rs#L132-L140) needs to use the path (with `PathBytes` as its type) since it's responsible for interfacing with the ibc-rs 02-client APIs. So, everything should be fine as it is. Right?

**Comment by srdtrk** [comment]
Yes, I believe so.
