### ISSUE TITLE
Extract validation step inside new client state creation and expose it as a separate method

### ISSUE THREAD

**Issue by Farhad-Shabani** [cosmos/ibc-rs#384]
## Improvement Summary

Separate validation from new client state creation method ([here](https://github.com/cosmos/ibc-rs/blob/ef52941e29aa2759e2861cdae8a7398b114cc5f2/crates/ibc/src/clients/ics07_tendermint/client_state.rs#L83))

## Proposal

- Client states received via an IBC message should be verifiable without having to create a new one. There should be a separate `validate()` method exposed to encompass all the fields' validation checks.
- The inclusion of validation steps inside new() may also lead to implementors forgetting to perform validations
- One use case is for upgrading client process.

**Comment by plafer** [comment]
I disagree that this is needed. The way I see it is that `new()` enforces the invariants of the object; that is, the object is created if and only if all invariants are true. It should then be used immutably. Exposing a `validate()` method suggests that the object could change within its lifetime, suggesting the following (discouraged) workflow:

1. Create the `ClientState` with valid parameters
2. mutate the `ClientState` in a way that violates one of the invariants
3. call `validate()`, and notice that an invariant was violated

Why not simply create a new object? I wouldn't be surprised that compiler optimizations optimize that away (e.g. reuse the same memory if the old `ClientState` is never reused). Can you point to a location in the code where you'd like to use this `validate()` method?

**Comment by Farhad-Shabani** [comment]
>  The way I see it is that new() enforces the invariants of the object; that is, the object is created if and only if all invariants are true.

A concern of mine about that `new()` method was that developers (who implement a new kind of client) can bypass that verification step or even forget about it. It is implemented on `ClientState` struct and this design does not enforce them to introduce any validation on their `ClientState` object. Though, neither the PR of this issue yet. I was figuring out how we can address this. What are your thoughts?

> Can you point to a location in the code where you'd like to use this validate() method? 

It could be used to validate fields of received `upgraded_client_state`. However, now, I am doing that by creating a new object as you mentioned.

Perhaps the least thing can be done in this regard, we change `new` method's name to the `new_validated`?! HW, it does not ease the above concern

**Comment by plafer** [comment]
I see your concern. I think we need to distinguish between the `ICS-2` and `ICS-7` (Tendermint) `ClientState`s. 

> A concern of mine about that new() method was that developers (who implement a new kind of client) can bypass that verification step or even forget about it.

## Tendermint light client

This is a Tendermint interface specific concern. IIUC, your concern is that it is not clear that `new()` performs validation. However, the interface [returns a `Result`](https://github.com/cosmos/ibc-rs/blob/a9b31980573422e4ec42718fb2f3930694fbe872/crates/ibc/src/clients/ics07_tendermint/client_state.rs#L95), which gives a strong signal that some sort of validation is expected in the function. However, I now see that we do need a constructor that doesn't do any validation, to be used in `ClientState::update_state_with_upgrade_client()`. So yes perhaps we could have `new()` and `new_validated()`?

## Light client developers

Since `new()`/`new_validated()` is a Tendermint-specific interface, developers implementing new clients will not see this function. They only interact with the ICS-2 `ClientState`. So the question to ask is: does our ICS-2 interface make it clear that we expect validation to be performed whenever a new client is created?

For new `ClientState`s coming from `UpgradeClient`, we have `ClientState::verify_upgrade_client()` (in your PR). Wouldn't that be obvious to developers that validation is expected there?

The other place we create new `ClientState`s is in the `CreateClient` handler, where [we call `decode_client_state()`](https://github.com/cosmos/ibc-rs/blob/a9b31980573422e4ec42718fb2f3930694fbe872/crates/ibc/src/core/ics02_client/handler/create_client.rs#L58). We indeed assume there that `ClientState` validation was done, and that should be properly documented. Therefore, the host (or blockchain) developer would read the docstring of `decode_client_state()`, and ensure to validate any light client that is returned to us.

I feel like this is sufficient (with the proposed changes) and that an additional `validate()` is redundant, and perhaps even confusing (e.g. a developer could ask "should I implement the validation in `verify_upgrade_client()`, as well as in `validate()`?").

WDYT?

**Comment by Farhad-Shabani** [comment]
Exactly. You well explained what I meant :ok_hand:
Let me digest this and take another look to the codebase, I'll get back to you

**Comment by Farhad-Shabani** [comment]
Finally, I could get into more detail :)

I noticed we already have another very similar method, called `validate_self_client`, which is exposed by `ConnectionReader` and soon would be available by `ValidationContext` interface.
The followings are related places in the codebase. Some go in one run doing multiple operations like “validate raw message(VR)” and “convert from Any(C)” or/and “validate client fields (VF)” or/and “create new client state (N)”:

1. “[create_client](https://github.com/cosmos/ibc-rs/blob/b3f921c5eb9f778f080757da14b399ddfa460006/crates/ibc/src/core/ics02_client/handler/create_client.rs#L58)” handler through `decode_client_state(Any)` (VR + C + VF + N) 
2. “[upgrade_client](https://github.com/cosmos/ibc-rs/blob/1fb3547a78e5dfa2c9bba99261a1f3a90de9bb7f/crates/ibc/src/clients/ics07_tendermint/client_state.rs#L873)” handler through `try_from(Any)` (VR + C + VF + N) 
3. “[conn_open_try](https://github.com/cosmos/ibc-rs/blob/aa97ced3f936dd0cb4bf586d340f36af4e5c986a/crates/ibc/src/core/ics03_connection/handler/conn_open_try.rs#L43)” handler through `validate_self_client(Any)` (VR + C + VF)
4. “[conn_open_ack](https://github.com/cosmos/ibc-rs/blob/9c9ad7c94ff9232ecea6348234695d9f78eb7f03/crates/ibc/src/core/ics03_connection/handler/conn_open_ack.rs#L229)” handler through `validate_self_client(Any)` (VR + C + VF)
5. “[validate_self_client](https://github.com/cosmos/ibc-rs/blob/691b27f9d8aaebe96d394047284be31adb7b17f4/crates/ibc/src/clients/ics07_tendermint/host_helpers.rs#L19)” under the `ValidateSelfClientContext` trait which is not used anywhere (VR + C + VF)
6. "[update_state_with_upgrade_client](https://github.com/cosmos/ibc-rs/blob/1fb3547a78e5dfa2c9bba99261a1f3a90de9bb7f/crates/ibc/src/clients/ics07_tendermint/client_state.rs#L968-L979)” through `TmClientState::new(...)` (N)

#### Remarks

- The logic sequences that already exist for the conversion always lead to a client state creation even calling (3) and (4). So, there, we’d also perform (VR + C + VF + N)
- The steps `decode_client_state` do, seem a bit difficult to understand from the developer’s perspective, IMO. we also have something else with the same name [here](https://github.com/cosmos/ibc-rs/blob/1fb3547a78e5dfa2c9bba99261a1f3a90de9bb7f/crates/ibc/src/clients/ics07_tendermint/client_state.rs#L1494-L1498)
- Looking at the `ibc-go`, [there](https://github.com/cosmos/ibc-go/blob/e093d85b533ab3572b32a7de60b88a0816bed4af/modules/core/03-connection/types/msgs.go#L118-L124) we have the “unpack_client_state” (VR + C  + N) and the “[validate](https://github.com/cosmos/ibc-go/blob/e650be91614ced7be687c30eb42714787a3bbc59/modules/core/exported/client.go#L41)” (VF)  under the `ClientState` interface. There, in any case, a client state instance is also created, but the fields are validated afterward

Validating fields is a client-specific activity and is conducted on messages. So, it would make sense to keep it out of *Ctx interfaces. Also, keeping it under the `ClientState` trait removes the need for a redundant conversion from `Any` to the client-specific type when it's called. Btw, Let me see how I'll end up in practice.

**Comment by Farhad-Shabani** [comment]
I tried to streamline some of the mentioned processes, but there are some entanglements. I made it "low-priority" to find a simple implementation after ADR05

**Comment by plafer** [comment]
We are touching some of the most confusing parts of IBC (IMO), which lead us to adopt the `of_x_on_y` convention to try to make as clear as possible.

> Validating fields is a client-specific activity and is conducted on messages. So, it would make sense to keep it out of *Ctx interfaces.

IIUC, you're saying that `validate_self_client()` should not be in `ValidationContext`. You got confused in the confusing part. Notice that `validate_self_client()` performs validation *of the client of us that's on the counterparty chain*. When opening a connection, we ask the relayer to give us the client *of us* that runs on the counterparty chain. We then decode it, and check that the parameters of it are appropriate. Now, the reason we have it as part of `ValidationContext` is because ibc-rs doesn't know *by design* how to decode `ClientState: Any` blobs, because we don' know all the clients installed on the host. For example, if the `TYPE_URL` for a `ClientState` blob is `"/some.unknown.consensus.protocol"`, how are we supposed to decode that? Only the host can do that; they will read the `TYPE_URL`, (presumably) recognize the type, and use the appropriate decoder to build the `ClientState`, and return it to us as a `dyn ClientState`. As previously stated, perhaps it would be appropriate to have an explicit validation on that `ClientState`, or very clearly document that it is the host's responsibility to make sure that the `ClientState` is valid.

Back to the `validate_self_client()`. *Note that this is a different validation than the one we do in `ClientState::new()`*. For example, we make sure that [the chain ID on that client is indeed our chain ID](https://github.com/cosmos/ibc-rs/blob/6f482c17b7a36a877b747ad90306abcbb30d40a8/crates/ibc/src/clients/ics07_tendermint/host_helpers.rs#L31-L39) (for Tendermint hosts). This addresses your point:

> 5. “[validate_self_client](https://github.com/cosmos/ibc-rs/blob/691b27f9d8aaebe96d394047284be31adb7b17f4/crates/ibc/src/clients/ics07_tendermint/host_helpers.rs#L19)” under the ValidateSelfClientContext trait which is not used anywhere (VR + C + VF)

The `ValidateSelfClientContext` trait is meant to be imported by Tendermint hosts, which they can use to implement `ValidationContext::validate_self_client()`. This is why it is not used internally. Let's document this better with #235.

I'm open to ideas to make any of this as clear as possible. Let me know if any of this is still unclear!

**Comment by Farhad-Shabani** [comment]
> Now, the reason we have it as part of ValidationContext is because ibc-rs doesn't know by design how to decode ClientState: Any blobs, because we don't know all the clients installed on the host. 

Ohh, I see! I could get the purpose of `validate_self_client` thanks to your clarification. 
Honestly, the design around this doesn't point you in the right direction and makes you do work to figure it out. I only found out about this necessary chain-specific context through this issue. otherwise didn’t notice such a thing should be abstracted for each chain.
I'm not sure if we can bond the context to force implementors to introduce a kind of self-chain interface!

> We are touching some of the most confusing parts of IBC (IMO), which lead us to adopt the of_x_on_y convention to try to make it as clear as possible

And yeah. some namings still use the legacy “counterparty” and the repo is not consistent yet.

Thank you so much for being patient. very helpful. Thus, to wrap up this tour :), should we just add some comments and make some naming adjustments, perhaps?

**Comment by plafer** [comment]
> Thus, to wrap up this tour :), should we just add some comments and make some naming adjustments, perhaps?

I believe so yes. Do you want to take a crack at it?

**Comment by Farhad-Shabani** [comment]
>I believe so yes. Do you want to take a crack at it? 

I'll take care of it 👍🏻

**Comment by Farhad-Shabani** [comment]
The concern will be addressed in #434
