### ISSUE TITLE
[ICS07] Investigate updating the store in `ClientState::initialize()` instead of `create_client::execute()`

### ISSUE THREAD

**Issue by Farhad-Shabani** [cosmos/ibc-rs#614]
## Summary

Looking at the [spec](https://github.com/cosmos/ibc/tree/main/spec/client/ics-007-tendermint-client#client-initialisation), we are missing the following check & setting upon initializing a Tendermint client state:

- assert(clientState.trustLevel >= 1/3 && clientState.trustLevel <= 1)
- provableStore.set("clients/{identifier}/clientState", clientState)

**Comment by plafer** [comment]
We do them, but in different but equivalent places:

> assert(clientState.trustLevel >= 1/3 && clientState.trustLevel <= 1)

Here: 
https://github.com/cosmos/ibc-rs/blob/707d032dac76c3e4b2c70a9dd4c508d03d67d62a/crates/ibc/src/clients/ics07_tendermint/client_state.rs#L102-L105

> provableStore.set("clients/{identifier}/clientState", clientState)

Here:
https://github.com/cosmos/ibc-rs/blob/707d032dac76c3e4b2c70a9dd4c508d03d67d62a/crates/ibc/src/core/ics02_client/handler/create_client.rs#L82

2 points:
1. the spec is very often out of date. Looking at [ibc-go](https://github.com/cosmos/ibc-go/blob/d3038f8317bbf4a9f43c578f7b6d4a6a5c4ebda5/modules/light-clients/07-tendermint/client_state.go#L194-L206) instead, see that it does not do (1) there either, but does (2).
2. Here, as in `ClientState::{update_state, update_state_on_misbehaviour}()`, they give the "mutating the store" responsibility to the light client instead of the core handler. I suspect that this comes as a realization that not all clients are updated the same (as we currently assume in ibc-rs). We should investigate whether that makes sense for us as well. Related: #615
