### ISSUE TITLE
Downgrade the borsh version

### ISSUE THREAD

**Issue by DaviRain-Su** [cosmos/ibc-rs#695]
## Bug Summary

- In near-sdk-rs: current used borsh version is 0.9: https://github.com/near/near-sdk-rs/blob/17b6cae68a7330f9b107e9aa13d192ca983f2945/near-sdk/Cargo.toml#L27
- In solana smart contract frame anchor borsh version is 0.9: https://github.com/coral-xyz/anchor/blob/2bf8afebd2f77f43a2e1e36bb4bf016fe2f289c8/lang/Cargo.toml#LL39C14-L39C14 

so, ibc-rs used borsh version should downgrade to 0.9

**Comment by Farhad-Shabani** [comment]
Done in #700

**Comment by plafer** [comment]
@DaviRain-Su anchor now [supports borsh v0.10](https://github.com/coral-xyz/anchor/blob/115679e67523016057e01c6d4bbf9d8e0a756874/lang/Cargo.toml#L51). We would like to move back to v0.10.*, since the sovereign SDK [uses it](https://github.com/Sovereign-Labs/sovereign-sdk/blob/2dae19d9a4421cc849a2349129089cb80f3dc028/Cargo.toml#L63). I believe the near-sdk should upgrade to v0.10 instead of everyone else staying on v0.9.

Would you be okay with us upgrading to v0.10?

**Comment by DaviRain-Su** [comment]
ye, I think is ok.
