### ISSUE TITLE
Compile errors of `v0.41.0` while only `serde` feature enabled

### ISSUE THREAD

**Issue by riversyang** [cosmos/ibc-rs#741]
## Problem Summary

During the integration of `ibc-rs v0.41.0` into [near-ibc](https://github.com/octopus-network/near-ibc.git), I got compile errors in the following places:

https://github.com/cosmos/ibc-rs/blob/349d7f5b259e2a34f1f9cbe730c1487e7ecffa38/crates/ibc/src/applications/transfer/packet.rs#L13-L25

https://github.com/cosmos/ibc-rs/blob/349d7f5b259e2a34f1f9cbe730c1487e7ecffa38/crates/ibc/src/core/ics02_client/events.rs#L135-L151

In `near-ibc` project, we only need to enable `borsh` and `serde` features of `ibc-rs`. So I checked source code and found that this is because the definition of `ibc_proto::ibc::applications::transfer::v2::FungibleTokenPacketData` and `ibc_proto::google::protobuf::Any` in `ibc-proto-rs v0.32.0` were defined as:

```rust
#[cfg_attr(feature = "std", derive(::serde::Serialize, ::serde::Deserialize))]
```

I have removed the feature condition from the derive statement for now, which allowed the code to compile. But I'm not sure whether I should commit this issue to `ibc-proto-rs`.

Anyway, I believe it would be worth discussing the issue in the `ibc-rs` implementation. It is important to determine whether the current implementation of the two mentioned places is necessary and appropriate.

**Comment by Farhad-Shabani** [comment]
Thanks @riversyang for laying out the problem so clearly. Yes, it’s the right place to discuss! 


### For a bit of context 

After [implementing ProtoJSON-compatible](https://github.com/cosmos/ics23/pull/146) **`Serialize`** and **`Deserialize`** on the ics23 Protobuf definitions using **`pbjson`** (which is not compatible with no-std envs) and then [re-exporting the ics23 type](https://github.com/cosmos/ibc-proto-rs/pull/92) in ibc-proto-rs, `serde` feature is no longer supported in no-std envs. And we put [restoring the no-std compatibility](https://github.com/cosmos/ibc-proto-rs/issues/98) on hold waiting to hear back before we dive into that.

### Possible remedy 
Yes! As you said and from what I see, those two impls look unnecessary:

1. The `serde` drive on `IbcEvent` (which required `serde` derive on `Any`) was added through [this PR](https://github.com/cosmos/ibc-rs/pull/321). Sounds like, initially, the intention was to derive only `parity-scale-codec` and `borsh`, but we ended up with an additional `serde` derive. Perhaps @DaviRain-Su can help us to clarify whether `serde` is needed there? If not, we can remove it.

2. Regarding `PacketData`, based on my checks, it seems safe to remove [these lines](https://github.com/cosmos/ibc-rs/blob/ee16dc2da38808e3c68c9bdf9fef42f69b3b627d/crates/ibc/src/applications/transfer/packet.rs#L15-L18). However, Should be noted we can't completely drop the `serde` since packet data is commonly serialized by JSON serde when sending over IBC.


Assuming no objections, this should work, and we can avoid changing `ibc-proto-rs`.

### A side question

IIRC, you were also using the `parity-scale-codec` feature before. Noticed that you no longer activate it (checked [this](https://github.com/octopus-network/near-ibc/tree/v1.0.0-pre.2) branch). Is it no longer needed?

**Comment by riversyang** [comment]
Thanks for the quick response, @Farhad-Shabani!

Regarding the `PacketData` struct, I agree with you that to remove the lines you mentioned while keeping the `serde` feature.

As for the `HeaderAttribute` struct, I believe it's necessary to keep the `serde` feature. JSON serialization is required for `IbcEvent` in certain cases, such as emitting the event via smart contract log text in `near-ibc` implementation. Since this struct is the only place where a type from `ibc-proto-rs` is used, would changing the type of the `header` field to `Vec<u8>` solve the issue more straightforwardly?

Lastly, to clarify, the `parity-scale-codec` feature is not required in `near-ibc` implementation and was mistakenly enabled before. It seems that it is for the `substrate-ibc` implementation.

**Comment by DaviRain-Su** [comment]
in near ibc maybe you can use borsh😃

**Comment by DaviRain-Su** [comment]
relate this relate no-std ： https://github.com/cosmos/ics23/pull/155 i working this， aim to enable ics23 serde to support no -std

**Comment by DaviRain-Su** [comment]
about issue: https://github.com/cosmos/ibc-rs/issues/753

**Comment by Farhad-Shabani** [comment]
> Regarding the PacketData struct, I agree with you that to remove the lines you mentioned while keeping the serde feature.

Check #763, please

> Since this struct is the only place where a type from ibc-proto-rs is used, would changing the type of the header field to Vec<u8> solve the issue more straightforwardly?

Opened #764

I don't know any other ways in `ibc-rs` to get this work. 
Sounds like we should follow it either in `ibc-proto-rs` or `pbjson` crate. 
Mark this as `blocked` till #753 gets fixed.

**Comment by dzmitry-lahoda** [comment]
oh, so many issues. what issue to track when it will be fixed?

**Comment by dzmitry-lahoda** [comment]
last working commit https://github.com/cosmos/ibc-rs/commit/2403dc3cef595454cf0629cfe15dcd8b176f56a9 . why not to revert breaking change until it fixed?

**Comment by Farhad-Shabani** [comment]
> oh, so many issues. what issue to track when it will be fixed?

Basically "restoring no_std compatibility" for ibc-proto-rs (reopened https://github.com/cosmos/ibc-proto-rs/issues/98). By which, then the [`serde` feature](https://github.com/cosmos/ibc-rs/blob/9cba2fc0421e52e8fc98ae8df3a77babc0f42be6/crates/ibc/Cargo.toml#L41-L42) would work for `no_std` envs.  

> last working commit https://github.com/cosmos/ibc-rs/commit/2403dc3cef595454cf0629cfe15dcd8b176f56a9 . why not to revert breaking change until it fixed?

There are projects dependent on ibc-proto-rs >= v0.32
