### ISSUE TITLE
Tendermint `ConsensusState -> Any` can crash if out of memory

### ISSUE THREAD

**Issue by plafer** [cosmos/ibc-rs#747]
[Here](https://github.com/cosmos/ibc-rs/blob/cd3a266cf4dda173a0c1797d84d984e3b36c3c19/crates/ibc/src/clients/ics07_tendermint/consensus_state.rs#L128). 

This probably involves updating tendermint-rs's `Protobuf` in a similar way that was done for the `Protobuf` in ibc-proto-rs (which removed the `Result` return for `encode_vec()`).

**Comment by DaviRain-Su** [comment]
I don't know, Why use https://github.com/cosmos/ibc-rs/blob/cd3a266cf4dda173a0c1797d84d984e3b36c3c19/crates/ibc/src/clients/ics07_tendermint/consensus_state.rs#L10 this Protobuf, otherwise ibc_proto::protobuf::Protobuf. 
https://github.com/cosmos/ibc-proto-rs/blob/9e87819bf686d2fd93d1e338943c9721fc0f3e50/src/protobuf/mod.rs#L74

I think this maybe help this.

**Comment by DaviRain-Su** [comment]
find this: https://github.com/informalsystems/tendermint-rs/pull/1093
